
Extraction of cooccurrence of all words, minus stopwords

```{r }
get_cooc

  if (by_sentence) {
    tokenized_txt <- txt |>
      tokenizers::tokenize_sentences()
  } else {
    tokenized_txt <- txt |>
      tokenizers::tokenize_paragraphs()
  }

tokenize
stopwords removal
cooc
more sw removal?
```

```{r}
token_by <- "sentence"
sw <- ""
count <- TRUE
lower <- F
```
```{r }
# Define the function
cooccur <- function(text, token_by = "sentence", sw = "", count = TRUE) {
  # sw <- sto::s2v("of by the a an in and was")
  if (nchar(text) < 1) {
    stop("the text is empty")
  }

  if (token_by == "sentence") {
    tokens <- tokenizers::tokenize_sentences(text)
  } else if (token_by == "paragraph") {
    tokens <- tokenizers::tokenize_paragraphs(text)
  } else {
    stop("Invalid token_type. Must be 'sentence' or 'paragraph'.")
  }

  # Clean stopwords
  word_tokens_list <- unlist(tokens) |> tokenizers::tokenize_words()
  cleaned_tokens <- lapply(word_tokens_list, function(x) Filter(function(word) !word %in% sw, x))

  # if list element smaller than 2, then erase it
  list_length <- cleaned_tokens |>
    lapply(length) |>
    lapply(\(x) {
      x > 2
    }) |>
    unlist()
  cleaned_tokens <- cleaned_tokens[list_length]

  if (length(cleaned_tokens) < 1) {
    stop("No words left after stopwords removal")
  }

  comb_list <- cleaned_tokens |>
    lapply(combn, 2, simplify = FALSE) |>
    unlist()

  pairs <- tibble::tibble(
    n1 = comb_list[seq(1, length(comb_list), by = 2)],
    n2 = comb_list[seq(2, length(comb_list), by = 2)]
  )

  if (count) {
    pairs <- pairs |> dplyr::count(n1, n2, sort = TRUE)
  }

  return(pairs)
}

# Example usage
text_ <- "Hello world. Hello R. How are you? I love to code. But we will check this second phrase. How was it possible?"
sw <- sto::s2v("and or the in a an for was")
cooccur(text_, token_by = "sentence", sw = c("and", "or", "but"))
cooccur(text, token_by = "sentence", sw = sw)
"apple banana orange. Apple banana cherry." |> cooccur()
text <- "Apple banana orange. Apple banana cherry."
```

