
Extraction of cooccurrence of all words, minus stopwords

```{r token test}
"bla bla ble-ble bli_bli blo1 blu.blu bla:ble bla/bli" |> 
  tokenizers::tokenize_words(strip_punct = F)

txt <- "Was ice-cream better in Soviet Union or in New York? Bla bla. The package https://quanteda.io/reference/index.html is very Nice! There are also compounded words like New_Jersey"
```
Preserva . _

```{r }
get_cooc

  if (by_sentence) {
    tokenized_txt <- txt |>
      tokenizers::tokenize_sentences()
  } else {
    tokenized_txt <- txt |>
      tokenizers::tokenize_paragraphs()
  }

tokenize
stopwords removal
cooc
more sw removal?
```

```{r params}
token_by <- "sentence"
token_by <- "par"
sw <- ""
count <- TRUE
lower <- F
lower <- T
loop <- FALSE
count <- TRUE
output <- "df"
output <- "df2"
output <- "lst"
```
```{r }
# Define the function
cooccur <- function(text, token_by = "sentence", sw = "", count = TRUE) {
  # sw <- sto::s2v("of by the a an in and was")
  if (nchar(text) < 1) {
    stop("the text is empty")
  }

  if (token_by == "sentence") {
    tokens <- tokenizers::tokenize_sentences(text)
  } else if (token_by == "paragraph") {
    tokens <- tokenizers::tokenize_paragraphs(text)
  } else {
    stop("Invalid token_type. Must be 'sentence' or 'paragraph'.")
  }

  # Clean stopwords
  word_tokens_list <- unlist(tokens) |> tokenizers::tokenize_words()
  cleaned_tokens <- lapply(word_tokens_list, function(x) Filter(function(word) !word %in% sw, x))

  # if list element smaller than 2, then erase it
  list_length <- cleaned_tokens |>
    lapply(length) |>
    lapply(\(x) {
      x > 2
    }) |>
    unlist()
  cleaned_tokens <- cleaned_tokens[list_length]

  if (length(cleaned_tokens) < 1) {
    stop("No words left after stopwords removal")
  }

  comb_list <- cleaned_tokens |>
    lapply(combn, 2, simplify = FALSE) |>
    unlist()

  pairs <- tibble::tibble(
    n1 = comb_list[seq(1, length(comb_list), by = 2)],
    n2 = comb_list[seq(2, length(comb_list), by = 2)]
  )

  if (count) {
    pairs <- pairs |> dplyr::count(n1, n2, sort = TRUE)
  }

  return(pairs)
}

# Example usage
text_ <- "Hello world. Hello R. How are you? I love to code. But we will check this second phrase. How was it possible?"
sw <- sto::s2v("and or the in a an for was")
cooccur(text_, token_by = "sentence", sw = c("and", "or", "but"))
cooccur(text, token_by = "sentence", sw = sw)
"apple banana orange. Apple banana cherry." |> cooccur()
text <- "Apple banana orange. Apple banana cherry."
```

```{r }
tbl_from_cooccur_list <- function(comb_list) {
  tibble::tibble(
    n1 = comb_list[seq(1, length(comb_list), by = 2)],
    n2 = comb_list[seq(2, length(comb_list), by = 2)]
  )
}
```

```{r prince plot graph2}
df_cooc <- ex_prince[1:4, "text"] |>
  unlist() |>
  cooccur_words(output = "df2")
```
```{r prince plot graph2}
text <- ex_prince[1:4, "text"] |> unlist()
DF <- cooccur_words(txt, output = "df2")

plot_graph2(DF, text)
```


```{r read DF2 cleaned}
df2 <- read.csv2("/home/alisson/Documentos/Programação/R/shared/UFBA/artigo_conspiracoes_Br/data/elastic_telegram_haarp_normalizado.csv") |>
  tibble::as_tibble() |>
  dplyr::mutate(date = lubridate::as_datetime(strict_date)) |>
  dplyr::select(date, chat_title, all_text, text, message_caption, sender_chat_id, id, chat_id)

df2
library(dplyr)
```
```{r }
txt <- df2 |>
  filter(!sto::grepl2(chat_title, "TARTARIA ITALIA INTERNATIONAL")) |>
  pull(all_text) |>
  tokenizers::tokenize_sentences() |>
  unlist() |>
  unname() |>
  unique()
# text <- txt
sw_all <- sto::s2v("the of a o e in de na no nas nos pra que do das dos") |> unique()

cooc <- cooccur_words(text = txt[1:20], sw_all, output = "df2")
dplyr::count(cooc, doc)
```
