
#' renumerate doc_id and sentence_id
#' @description
#' renumerate doc_id and sentence_id
#' @param pos_df a dataframe generated by spacyr::spacy_parse
renum_pos <- function(pos_df) {
  pos_df |>
  dplyr::mutate(
    sentence_id = gsub("text(.*)", "\\1", doc_id),
    doc_id = paste0("text", x))
  }
