
```{r }
cooc_parsim <- cooc |> mutate(n = ifelse(n > threshold, threshold, n))

cooc_parsim2 <- cooc_parsim |>
  group_by(n1, n2) |>
  summarize(n = sum(n)) |>
  arrange(-n) |>
```

```{r }
#' Transform and Summarize Co-occurrence Data
#'
#' This function transforms a co-occurrence dataframe by capping counts above a threshold,
#' groups the data by two columns, sums the counts within each group, and arranges the results in descending order.
#'
#' @param cooc A dataframe containing co-occurrence data with at least columns 'n1', 'n2', and 'n'.
#' @param threshold The threshold max value above which counts are capped in each document.

#' @return A transformed dataframe with summed counts arranged by their magnitude.

#' @examples

#' # Example usage:
#' cooc_data <- data.frame(n1 = c(1, 1, 2), n2 = c(3, 4, 3), n = c(5, 6, 7))
#' restrict_freq(cooc_data, threshold = 5)
restrict_freq <- function(cooc, threshold) {
  cooc |>
    mutate(n = ifelse(n > threshold, threshold, n)) |>
    group_by(n1, n2) |>
    summarize(n = sum(n)) |>
    arrange(-n)
}
```


